import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import type { WizardAnswers } from './types';

export async function generateEnv(answers: WizardAnswers): Promise<void> {
  const envPath = path.join(process.cwd(), '.env');

  // Backup si .env existant
  if (fs.existsSync(envPath)) {
    const backup = envPath + `.backup.${Date.now()}`;
    fs.copyFileSync(envPath, backup);
    console.log(`📁 Ancien .env sauvegardé : ${backup}`);
  }

  const jwtSecret = answers.JWT_SECRET || crypto.randomBytes(32).toString('base64');
  const dbPass    = answers.DB_PASSWORD || crypto.randomBytes(16).toString('hex');
  const redisPass = answers.REDIS_PASSWORD || crypto.randomBytes(16).toString('hex');

  const lines: string[] = [
    '# ╔══════════════════════════════════════╗',
    '# ║   INTRACLAW — Generated by Wizard   ║',
    `# ║   ${new Date().toISOString()}         ║`,
    '# ╚══════════════════════════════════════╝',
    '',
    '# ── AI Models ──────────────────────────',
    `ANTHROPIC_API_KEY=${answers.ANTHROPIC_API_KEY}`,
    '',
    '# ── Database ───────────────────────────',
    `DB_PASSWORD=${dbPass}`,
    `REDIS_PASSWORD=${redisPass}`,
    '',
    '# ── Telegram ───────────────────────────',
    `ENABLE_TELEGRAM=${answers.ENABLE_TELEGRAM}`,
    `TELEGRAM_BOT_TOKEN=${answers.TELEGRAM_BOT_TOKEN ?? ''}`,
    `TELEGRAM_CHAT_ID=${answers.TELEGRAM_CHAT_ID ?? ''}`,
    '',
    '# ── WhatsApp ───────────────────────────',
    `ENABLE_WHATSAPP=${answers.ENABLE_WHATSAPP}`,
    '',
    '# ── Discord ────────────────────────────',
    `ENABLE_DISCORD=${answers.ENABLE_DISCORD}`,
    `DISCORD_TOKEN=${answers.DISCORD_TOKEN ?? ''}`,
    '',
    '# ── Slack ──────────────────────────────',
    `ENABLE_SLACK=${answers.ENABLE_SLACK}`,
    `SLACK_BOT_TOKEN=${answers.SLACK_BOT_TOKEN ?? ''}`,
    `SLACK_SIGNING_SECRET=${answers.SLACK_SIGNING_SECRET ?? ''}`,
    `SLACK_APP_TOKEN=${answers.SLACK_APP_TOKEN ?? ''}`,
    '',
    '# ── Gmail ──────────────────────────────',
    `ENABLE_GMAIL=${answers.ENABLE_GMAIL}`,
    'GOOGLE_CLIENT_ID=',
    'GOOGLE_CLIENT_SECRET=',
    'GOOGLE_REDIRECT_URI=http://localhost:3000/auth/google/callback',
    'GOOGLE_REFRESH_TOKEN=',
    '',
    '# ── Google Calendar ────────────────────',
    `ENABLE_GOOGLE_CALENDAR=${answers.ENABLE_GOOGLE_CALENDAR}`,
    '',
    '# ── Notion ─────────────────────────────',
    `ENABLE_NOTION=${answers.ENABLE_NOTION}`,
    `NOTION_TOKEN=${answers.NOTION_TOKEN ?? ''}`,
    '',
    '# ── User Profile ───────────────────────',
    `USER_NAME=${answers.USER_NAME}`,
    `USER_TIMEZONE=${answers.USER_TIMEZONE}`,
    `USER_LANGUAGE=${answers.USER_LANGUAGE}`,
    '',
    '# ── Security ───────────────────────────',
    `JWT_SECRET=${jwtSecret}`,
    '',
    '# ── IntraClaw Settings ─────────────────',
    'LOOP_ENABLED=true',
    'LOOP_INTERVAL_MS=300000',
    'LOG_LEVEL=info',
    '',
    '# ── Media Generation ───────────────────',
    'FAL_KEY=',
    'ELEVENLABS_API_KEY=',
    '',
    '# ── Home Assistant ─────────────────────',
    'HA_URL=',
    'HA_TOKEN=',
  ];

  fs.writeFileSync(envPath, lines.join('\n') + '\n', 'utf-8');
  console.log(`✅ .env généré : ${envPath}`);
}
